<a href="https://colab.research.google.com/github/JerinRaj20/Assignment_Py/blob/main/Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Question 1, year to reach 100

name = input('Enter your name')
age = int(input('Enter your current age'))
cur = 2022

def year_predictor_100(name, age):
  diff_year = 100 - age
  year_to_reach = cur + diff_year
  print(name ,'will reach 100 years in',' ', year_to_reach)

year_predictor_100(name,age)


Enter your nameJerin
Enter your current age90
Jerin will reach 100 years in   2032


In [ ]:
#Question 2, pandas group by

import pandas as pd

df = pd.DataFrame()
print(df)

list1 = list(range(5))

list2 = [[1,10],[1,20],[3,30]]

df = pd.DataFrame(list2,index=[1,2,3], columns=['Sl_No', 'Marks'])
df
df.groupby(['Sl_No'])['Marks'].sum()

Empty DataFrame
Columns: []
Index: []


Sl_No
1    30
3    30
Name: Marks, dtype: int64

In [ ]:
#Question 3

list2 = [[1,10],[1,20],[3,30]]

df = pd.DataFrame(list2,index=[1,2,3], columns=['Sl_No', 'Marks'])

df

Sl_No  Marks
1      1     10
2      1     20
3      3     30

In [ ]:
#Question 4

#Combine data frames

list1 =[['Banking',1000],['Sports', 2000],['Tourism', 500]]
df = pd.DataFrame(list1, columns=['Category','Income in crores'])
df

## adding extra column into the data frame

df['Rating'] =[1,2,3]
df

## Append function


list2 =[['Federal',1000],['Cricket', 2000],['Hill Station', 500]]
df2 = pd.DataFrame(list2, columns=['Category','Income in crores'])
print(df)
print(df2)

df.append(df2)

  Category  Income in crores  Rating
0  Banking              1000       1
1   Sports              2000       2
2  Tourism               500       3
       Category  Income in crores
0       Federal              1000
1       Cricket              2000
2  Hill Station               500


Category  Income in crores  Rating
0       Banking              1000     1.0
1        Sports              2000     2.0
2       Tourism               500     3.0
0       Federal              1000     NaN
1       Cricket              2000     NaN
2  Hill Station               500     NaN

In [ ]:
# Question 5

#List and Tuples differance in python

#List is mutable, tuples is non mutable

list1 =[1,2,3]
list1.append(4)
list1

tuple1 =(1,2,3)
tuple1.append(4)
type(tuple1)

AttributeError: ignored

In [3]:
# Question 6
#Mean, median and Standard deviation of numpy array

import numpy as np
array1= np.array([1,5,3,100,4,48])
print('Median :' , np.median(array1))
print('Mean :' , np.mean(array1))
print('Standard deviation :', np.std(array1))


Median : 4.5
Mean : 26.833333333333332
Standard deviation : 36.59424666377065


In [6]:
#Question 7
#Remove duplictaes from list

list1 = [1,1,2,3,3,3,4,5]
list2 = list(set(list1))
list2

[1, 2, 3, 4, 5]

In [7]:
#Question 8
#used to map a specific math fun to the list

list1 = [1,6,8,7,1]
list2 = list(map(lambda x : x*2,list1))
print(list2)

[2, 12, 16, 14, 2]


In [9]:
x = [5,7,6]
for i in x :
  pass
  print(i)

5
7
6


In [15]:
#stack in python

p1=np.array([[81,82,3],[4,8,6]])
p2=np.array([[2,2,9],[1,11,2]])
print (np.vstack((p1,p2)))

[[81 82  3]
 [ 4  8  6]
 [ 2  2  9]
 [ 1 11  2]]
